social_site/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name ='login'),
    path('signup/',views.SignUp.as_view(),name = 'signup'),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('profile_page/',views.MyProfileView.as_view(),name='profile_page'),

    path('update_profile/<slug>/',views.ProfileUpdateView.as_view(),name='update_profile'),
    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'),
        name="reset_password"),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_form.html'),
        name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name = "accounts/password_rest_done.html"),
        name='password_reset_complete'),

    path('user_list/',
        views.users_list.as_view(),
        name = 'user_list'),

    path('friend_list/<slug>/',
        views.friend_list.as_view(template_name = 'accounts/friend_list.html'),
        name = 'friend_list'),

    path('users/<slug>/',
        views.user_profile.as_view(),
        name = 'user_profile'),

    path('users/friend-request/send/<int:id>',views.send_friend_request,
        name = 'send_friend_request'),

    path('users/friend-request/cancel/<int:id>',views.cancel_friend_request,
        name = 'cancel_friend_request'),

    path('users/friend-request/accept/<int:id>',views.accept_friend_request,
        name = 'accept_friend_request'),

    path('users/friend_request/decline/<int:id>',views.decline_friend_request,
        name = 'decline_friend_request'),

    path('users/delete_friend/<int:id>',views.delete_friend,name = 'delete_friend'),

    path('search_users/',views.search_users.as_view(),name = 'search_users'),

]

social_site/feed/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = 'feed'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list_view'),
    path('post/<int:pk>/like',views.like,name='post_like'),
    path('post/new/',views.CreatePost.as_view(),name = 'create_post'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail_view'),
    path('post/by/<slug>/',views.UserPostListView.as_view(),name='user_posts'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/<int:pk>/comment/',views.CommentView.as_view(),name='new_comment'),
    path('post/<int:pk>/comments/',views.PostCommentList.as_view(),name='post_comments'),
    path('post/search/',views.SearchPosts.as_view(),name='search_posts'),
]

social_site/social_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name = 'home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('feed/',include('feed.urls',namespace = 'feed')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social_site/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Social site</title>

  <!-- bootstrap -->
  <!-- CSS only -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'CSS/mysite.css' %}">

  <!-- Alternative to Bootstrap 3 Glyphicons -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Optional theme -->
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</head>

<body>

  <nav class='navbar nav navbar-expand'  id="mynavbar">
    <!-- <div class="container"> -->
      <div class="navbar-header">
        <a class="navbar-brand " href="{%url 'home'%}">Social Site</a>
      </div>
      <div class="">
        <ul class="navbar-nav navbar-right" >
          {% if request.user.is_authenticated %}
            <li><a class="navbar-item ml-2 mr-2" href="{% url 'feed:create_post' %}">Create Post</a></li>
            <li><a class="nav-item ml-2 mr-2" href="{% url 'feed:post_list_view' %}">All Posts</a></li>
            <li><a class="nav-item ml-2 mr-2" href="{% url 'accounts:user_list' %}">Users</a></li>
            <li><a class="nav-item ml-2 mr-2" href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span>Log Out</a></li>
            <li><a class ='nav-item ml-2 mr-2' href="{% url 'accounts:profile_page' %}"><span class="glyphicon glyphicon-user"></span></a></li>
          {%else%}
            <li><a class="navbar-text ml-2 mr-2" href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
            <li><a class="navbar-text ml-2 mr-2" href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span>Sign UP</a></li>
          {%endif%}
        </ul>
      </div>
  </nav>
  <div class="container-fluid content-class">
    {% block content %}

    {% endblock %}
  </div>

</body>

</html>

social_site/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Social site</title>

  <!-- bootstrap -->
  <!-- CSS only -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'CSS/mysite.css' %}">

  <!-- Alternative to Bootstrap 3 Glyphicons -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Optional theme -->
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</head>

<body class='home-content'>

  <nav class='navbar nav navbar-expand' >
    <!-- <div class="container"> -->
      <div class="navbar-header">
        <a class="navbar-brand " href="{%url 'home'%}">Social Site</a>
      </div>
      <div class="">
        <ul class="navbar-nav navbar-right ml-auto" >
          {% if request.user.is_authenticated %}
            <li><a class="navbar-item ml-2 mr-2" href="{% url 'feed:create_post' %}">Create Post</a></li>
            <li><a class="nav-item ml-2 mr-2" href="{% url 'feed:post_list_view' %}">All Posts</a></li>
            <li><a class="nav-item ml-2 mr-2" href="{% url 'accounts:user_list' %}">Users</a></li>
            <li><a class="nav-item ml-2 mr-2" href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span>Log Out</a></li>

            <li><a class ='nav-item ml-2 mr-2' href="{% url 'accounts:profile_page' %}"><span class="glyphicon glyphicon-user"></span></a></li>
          {%else%}
            <li><a class="navbar-text ml-2 mr-2" href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
            <li><a class="navbar-text ml-2 mr-2" href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span>Sign UP</a></li>
          {%endif%}
        </ul>


      </div>
  </nav>
  <div class="container-fluid">
      <h1 style='text-align:center;margin-top:25vh;' >Welcome to social_site</h1>
  </div>

</body>

</html>