social_site/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name ='login'),
    path('signup/',views.SignUp.as_view(),name = 'signup'),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('profile_page/',views.MyProfileView.as_view(),name='profile_page'),

    path('update_profile/<slug>/',views.ProfileUpdateView.as_view(),name='update_profile'),
    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'),
        name="reset_password"),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_form.html'),
        name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name = "accounts/password_rest_done.html"),
        name='password_reset_complete'),

    path('user_list/',
        views.users_list.as_view(),
        name = 'user_list'),

    path('friend_list/<slug>/',
        views.friend_list.as_view(template_name = 'accounts/friend_list.html'),
        name = 'friend_list'),

    path('users/<slug>/',
        views.user_profile.as_view(),
        name = 'user_profile'),

    path('users/friend-request/send/<int:id>',views.send_friend_request,
        name = 'send_friend_request'),

    path('users/friend-request/cancel/<int:id>',views.cancel_friend_request,
        name = 'cancel_friend_request'),

    path('users/friend-request/accept/<int:id>',views.accept_friend_request,
        name = 'accept_friend_request'),

    path('users/friend_request/decline/<int:id>',views.decline_friend_request,
        name = 'decline_friend_request'),

    path('users/delete_friend/<int:id>',views.delete_friend,name = 'delete_friend'),

    path('search_users/',views.search_users.as_view(),name = 'search_users'),

]

social_site/feed/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = 'feed'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list_view'),
    path('post/<int:pk>/like',views.like,name='post_like'),
    path('post/new/',views.CreatePost.as_view(),name = 'create_post'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail_view'),
    path('post/by/<slug>/',views.UserPostListView.as_view(),name='user_posts'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/<int:pk>/comment/',views.CommentView.as_view(),name='new_comment'),
    path('post/<int:pk>/comments/',views.PostCommentList.as_view(),name='post_comments'),
    path('post/search/',views.SearchPosts.as_view(),name='search_posts'),
]

social_site/social_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name = 'home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('feed/',include('feed.urls',namespace = 'feed')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social_site/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse
from django.utils import timezone


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(default='default.jpg',upload_to='profile_pic')
    slug = AutoSlugField(populate_from='user')
    bio = models.CharField(max_length = 100, blank = True)
    friends = models.ManyToManyField('Profile',blank = True)

    def __str__(self):
        return f'@{self.user.username}'

    def get_absolute_url(self):
        return "users/{}".format(self.slug)


def post_save_user_model_receiver(sender,instance,created,*args,**kwargs):
    if(created):
        try:
            Profile.objects.update(user=instance)
        except:
            pass

post_save.connect(post_save_user_model_receiver,sender=settings.AUTH_USER_MODEL)

class FriendRequest(models.Model):
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="to_user", on_delete=models.CASCADE)
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = 'from_user', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "from {} to {}".format(self.from_user.username, self.to_user.username)

social_site/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile


class UserCreateForm(UserCreationForm):

    email = forms.EmailField()

    class Meta():
        fields = ['username','password1','password2','email']
        model = get_user_model()

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)

            self.fields['username'].label = "Display Name"
            self.fields['email'].label = "Email Adress"

class ProfileUpdateForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = ['image','bio']

social_site/accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy,reverse
from . import models
from django.views import generic
from django.contrib.auth.decorators import login_required

from braces.views import SelectRelatedMixin
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin

from . import forms
from django.contrib.auth import get_user_model

from django.http import HttpResponseRedirect
User = get_user_model()
# Create your views here.

class SignUp(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

class MyProfileView(generic.TemplateView):
    template_name = 'accounts/my_profile_page.html'

class users_list(generic.ListView):
    model = models.Profile
    template_name = 'accounts/user_list.html'

    def get_queryset(self):
        return models.Profile.objects.exclude(user=self.request.user)

class friend_list(generic.ListView):
    model = models.Profile
    template_name = 'accounts/friend_list.html'

    def get_queryset(self):
        user = get_object_or_404(models.Profile, slug = self.kwargs.get('slug'))
        # print("user : {}".format(user))
        return user.friends.all()
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['list_user_profile'] = get_object_or_404(models.Profile, slug = self.kwargs.get('slug'))
        return context

class user_profile(generic.DetailView):
    template_name = 'accounts/profile_detail.html'
    queryset = models.Profile.objects.all()
    # print("hello")
    # print(queryset)

    def get_object(self):
        # print("hello 1")
        # print(self.kwargs.get('slug'))
        return get_object_or_404(models.Profile, slug=self.kwargs.get('slug'))

    def get_context_data(self,*args,**kwargs):
        context = super(user_profile, self).get_context_data(*args,**kwargs)

        p = models.Profile.objects.filter(slug = self.kwargs.get('slug')).first()
        u = p.user

        friends = p.friends.all()

        sent_friend_request = models.FriendRequest.objects.filter(from_user = u)
        rec_friend_request = models.FriendRequest.objects.filter(to_user = u)
        # user_posts = Post.objects.filter(user_name=u)
        button_status = 'none'
        # print(self.request.user)
        # print(User.objects.first())
        # print(p)
        # print("user friends {}".format(u.profile.friends.all()))
        if self.request.user.profile not in u.profile.friends.all():
            button_status = 'not_friend'
        else :
            button_status = 'friend'

        # if we have sent him a friend request
        if len(models.FriendRequest.objects.filter(
        from_user = self.request.user).filter(to_user = p.user))==1:
            button_status = 'friend_request_sent'
        # if len(models.FriendRequest.objects.filter(from_user=self.request.user).filter(to_user=p.user)) == 1:
		# 	button_status = 'friend_request_sent'

		# if we have recieved a friend request
        if len(models.FriendRequest.objects.filter(
        from_user=p.user).filter(to_user=self.request.user))==1:
            button_status = 'friend_request_received'
		# if len(models.FriendRequest.objects.filter(
        # from_user=p.user).filter(to_user=self.request.user)) == 1:
		# 		button_status = 'friend_request_received'

        context['u']=u
        context['button_status'] = button_status
        context['friends'] = friends
        context['sent_friend_request'] = sent_friend_request
        context['rec_friend_request'] = rec_friend_request
        # context['post_count'] = user.posts.count

        return context

class ProfileUpdateView(LoginRequiredMixin,UserPassesTestMixin,generic.UpdateView):
    model = models.Profile
    # fields = ['image','bio']
    form_class = forms.ProfileUpdateForm
    template_name = 'accounts/profile_update_page.html'
    def test_func(self):
        curr_user = get_object_or_404(User, username = self.request.user.username)
        profile = self.get_object()
        if profile.user == curr_user:
            return True
        return False

    def get_success_url(self):
        user = get_object_or_404(User, username__iexact  = self.request.user.username)
        print(user.username)
        return reverse_lazy('accounts:profile_page')

@login_required
def send_friend_request(request, id):
    t_user = get_object_or_404(User, id=id)
    f_user = User.objects.first()
    frequest = models.FriendRequest.objects.get_or_create(
        from_user = f_user,
        to_user = t_user
    )
    return HttpResponseRedirect('/accounts/profile_page/')

@login_required
def cancel_friend_request(request,id):
    t_user = get_object_or_404(User, id=id)
    frequest = models.FriendRequest.objects.filter(
        from_user = request.user,
        to_user = t_user
    )
    frequest.delete()
    return HttpResponseRedirect('/accounts/profile_page/')

@login_required
def accept_friend_request(request, id):
    f_user = get_object_or_404(User, id=id) # from_user
    frequest = models.FriendRequest.objects.filter(
        from_user = f_user,
        to_user = request.user
    ).first()
    user1 = frequest.to_user
    user2 = f_user
    user1.profile.friends.add(user2.profile)
    user2.profile.friends.add(user1.profile)
    if(models.FriendRequest.objects.filter(from_user=request.user, to_user=f_user).first()):
        reverse_req = models.FriendRequest.objects.filter(f_user=request.user,to_user=f_user).first()
        reverse_req.delete()
    frequest.delete()
    return HttpResponseRedirect('/accounts/profile_page')

@login_required
def decline_friend_request(request,id):
    f_user = get_object_or_404(User, id=id)
    frequest = models.FriendRequest.objects.filter(
        from_user = f_user,
        to_user = request.user
    ).first()
    frequest.delete()

def delete_friend(request, id):
    f_user = get_object_or_404(User, id=id)
    print("user is {}".format(f_user))
    f_user.profile.friends.remove(request.user.profile)
    request.user.profile.friends.remove(f_user.profile)
    return HttpResponseRedirect('/accounts/profile_page')

# @login_required
# def search_users(request):
#     query = request.GET.get('q')
#     object_list = User.objects.filter(username__icontains=query)
#     context = {
#         'users':object_list
#     }
#     return render(request,'accounts/users/search_users.html',context)

class search_users(generic.ListView):
    model = User
    template_name = 'accounts/search_users.html'
    # print("hello")
    def get_queryset(self,**kwargs):
        query = self.request.GET.get('user_name')
        # print('hello{}'.format(query))
        object_list = User.objects.filter(username__icontains=query)
        return object_list
        # context = super().get_context_data(**kwargs)
        # print(self.request.GET.get('user_name'))
        # name = self.request.GET.get('user_name')
        # context['search_results']=User.objects.filter(username__icontains=name)
        # return context
# TODO : edit profile

social_site/accounts/templates/accounts/friend_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <h1>Friends of user {{list_user_profile.user}} : </h1>
  <div class="">
    <ul>
      {% for name in object_list  %}
        <br><li>
            <a href="{% url 'accounts:user_profile' slug=name|slugify %}">{{name}}</a>
        </li>
      {%endfor%}
    </ul>

  </div>
{% endblock %}

social_site/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input class="submit-button" type="submit" class="btn btn-default" value="Login">
  </form>
</div>
{% endblock %}

social_site/accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Thanks for visiting the Website!</h1>
    <a href="{% url 'home' %}">Go to home page</a>
  </body>
</html>

social_site/accounts/templates/accounts/my_profile_page.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div>
    <div class="">
      <h1>Your Profile</h1>
      <p>
        <a href="{% url 'accounts:update_profile' slug=user.profile.slug %}"><span class='glyphicon glyphicon-pencil'></span></a>
      </p>
      <br>
    </div>
    <div class="media">
      <br>
      <img class = 'rounded-circle account-img' src="{{ user.profile.image.url }}" alt=""
        width="75" height="75">
      <div class="media-body">
        <h2>{{user.username}}</h2>
        <p class = 'text-secondary'>{{user.email}}</p>
      </div>
    </div>
    {% if user.profile.bio|length %}
      BIO: {{user.profile.bio}}
    {% else %}
      <p>You haven't set your bio yet, set it now in profile update!</p>
    {% endif %}
    <br>
    <a href="{% url 'accounts:reset_password' %}">Change Password</a>
  </div>

  <div class="">
    <p>You have
      <a href="{% url 'accounts:friend_list' slug=user.profile.slug %}">
      {{ user.profile.friends.count }}</a> friends</p>
  </div>

  <br>

  <a href="{% url 'feed:user_posts' slug=user.profile.slug %}">My Posts</a>




{% endblock %}

social_site/accounts/templates/accounts/password_reset.html
<h1>Password Reset</h1>
<h2>Forgotten your password? Enter your email below and we will send you a
verification mail to reset your password.</h2>
<form  method="post">
  {%csrf_token %}
  {{form}}
  <input type="submit" name="" value="send email">
</form>

social_site/accounts/templates/accounts/password_reset_form.html
<h2>Enter New Password</h2>
<p>Please enter your new password twice so that we can verify you typed it
correctly</p>

<form class=""  method="post">
  {%csrf_token%}
  {{form}}
  <input type="submit" name="" value="submit">
</form>

social_site/accounts/templates/accounts/password_reset_sent.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  <h2>We have sent an email to your provided email address, please verify.</h2>
</body>

</html>

social_site/accounts/templates/accounts/password_rest_done.html
<h2>Password reset complete</h2>
<p>Your password has been set, you may go ahead and login with it now</p>

<a href="{% url 'accounts:login' %}">Login</a>

social_site/accounts/templates/accounts/profile_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div>
    <div class="media">
      <img class = 'rounded-circle account-img' src="{{ object.user.profile.image.url }}" alt=""
        width="75" height="75">
      <div class="media-body">
        <h2>{{object.user.username}}</h2>
        <p class = 'text-secondary'>{{object.user.email}}</p>
      </div>
    </div>
    <!-- <a href="{% url 'accounts:reset_password' %}">Change Password</a> -->
  </div>
  {% if object.user.profile.bio|length %}
    <p>USER's BIO:  {{object.user.profile.bio}}</p>
  {% else %}
    <p>User is yet to set his/her bio.</p>
  {% endif %}
  <br>
  <p>Status with user : {{button_status}} </p>
  {% if button_status == 'not_friend' %}
    <a href="{% url 'accounts:send_friend_request' id=object.user.id%}">
      <button type="button" name="button">Make Friend</button>
    </a>
  {% endif %}
  {% if button_status == 'friend_request_sent' %}
    <a href="{% url 'accounts:cancel_friend_request' id=object.user.id%}">
      <button type="button" name="button">cancel friend request</button>
    </a>
  {% endif %}
  {% if button_status == 'friend_request_received' %}
    <a href="{% url 'accounts:accept_friend_request' id=object.user.id%}">
      <button type="button" name="button">accept</button>
    </a>
    <a href="{% url 'accounts:decline_friend_request' id=object.user.id%}">
      <button type="button" name="button">reject</button>
    </a>
  {% endif %}
  {% if button_status == 'friend' %}
    <a href="{% url 'accounts:delete_friend' id=object.user.id%}">
      <button type="button" name="button">delete friend</button>
    </a>
  {% endif %}

  <div class="">
    <br><br>
    <p>Friends of user: </p>
    {% for u in friends %}
      <!-- <p>{{u}}</p> -->
      {% if u.user != user %}
        <a href="{% url 'accounts:user_profile' slug=u|slugify %}">{{u}}<br></a>
      {% endif %}
    {% endfor %}
  </div>

  <div class="">
    <br><br>
    <a href="{% url 'feed:user_posts' slug=u|slugify %}">Posts by {{object.user}}</a>

  </div>

  <!-- <div class="">
    <p>The user has
      <a href="{% url 'accounts:friend_list' slug=object.user.profile.slug %}">
      {{ object.user.profile.friends.count }}</a> friends</p>
  </div> -->

{% endblock %}

social_site/accounts/templates/accounts/profile_update_page.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
  <form class="" action="" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="confirm">
  </form>
{% endblock %}

social_site/accounts/templates/accounts/search_users.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <form action="{% url 'accounts:search_users' %}" method="get">
    <input type="text" name="user_name" placeholder="search">
  </form>
  <h1>Search Results</h1>
  <div class="">
    <ul>
      {% for user in object_list  %}
        <br><li><a href="{% url 'accounts:user_profile' slug=user|slugify %}">
        {{user}}</a></li>
      {%endfor%}
    </ul>

  </div>

{% endblock %}

social_site/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Signup</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input class="submit-button" type="submit" class="btn btn-default" value="Login">
  </form>

</div>
{% endblock %}

social_site/accounts/templates/accounts/user_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <form action="{% url 'accounts:search_users' %}" method="get">
    <input type="text" name="user_name" placeholder="search">
  </form>
  <h1>These are the users</h1>
  <div class="">
    <ul>
      {% for user in object_list  %}
        <br><li><a href="{% url 'accounts:user_profile' slug=user|slugify %}">
        {{user}}</a></li>
      {%endfor%}
    </ul>

  </div>

{% endblock %}