social_site/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name ='login'),
    path('signup/',views.SignUp.as_view(),name = 'signup'),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('profile_page/',views.MyProfileView.as_view(),name='profile_page'),

    path('update_profile/<slug>/',views.ProfileUpdateView.as_view(),name='update_profile'),
    path('reset_password/',
        auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'),
        name="reset_password"),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_form.html'),
        name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(template_name = "accounts/password_rest_done.html"),
        name='password_reset_complete'),

    path('user_list/',
        views.users_list.as_view(),
        name = 'user_list'),

    path('friend_list/<slug>/',
        views.friend_list.as_view(template_name = 'accounts/friend_list.html'),
        name = 'friend_list'),

    path('users/<slug>/',
        views.user_profile.as_view(),
        name = 'user_profile'),

    path('users/friend-request/send/<int:id>',views.send_friend_request,
        name = 'send_friend_request'),

    path('users/friend-request/cancel/<int:id>',views.cancel_friend_request,
        name = 'cancel_friend_request'),

    path('users/friend-request/accept/<int:id>',views.accept_friend_request,
        name = 'accept_friend_request'),

    path('users/friend_request/decline/<int:id>',views.decline_friend_request,
        name = 'decline_friend_request'),

    path('users/delete_friend/<int:id>',views.delete_friend,name = 'delete_friend'),

    path('search_users/',views.search_users.as_view(),name = 'search_users'),

]

social_site/feed/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url

app_name = 'feed'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list_view'),
    path('post/<int:pk>/like',views.like,name='post_like'),
    path('post/new/',views.CreatePost.as_view(),name = 'create_post'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail_view'),
    path('post/by/<slug>/',views.UserPostListView.as_view(),name='user_posts'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/<int:pk>/comment/',views.CommentView.as_view(),name='new_comment'),
    path('post/<int:pk>/comments/',views.PostCommentList.as_view(),name='post_comments'),
    path('post/search/',views.SearchPosts.as_view(),name='search_posts'),
]

social_site/social_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name = 'home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('feed/',include('feed.urls',namespace = 'feed')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

social_site/feed/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    description = models.CharField(max_length = 255, blank = True)
    pic = models.ImageField(default='default.jpg',upload_to='images/')
    date_posted = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, related_name='posts',
        null=True, blank = True, on_delete=models.CASCADE)
    tags = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('posts:post-detail',kwargs={'pk':self.pk})

class Comment(models.Model):
    Post = models.ForeignKey(Post, related_name='comments',
        on_delete = models.CASCADE)
    user = models.ForeignKey(User, related_name='comments',
        null=True, blank = True, on_delete=models.CASCADE)
    message = models.CharField(max_length = 255, blank = False)
    # difference between auto_now & timezone.now :
    # default = timezone.now means user can edit the date of creation while making
    # comment while auto_now = True means user doesn't have control and it will be
    # the date of saving of comment by default
    date = models.DateTimeField(auto_now=True)

class Like(models.Model):
    user = models.ForeignKey(User, related_name='likes',
        null=True, blank = True, on_delete=models.CASCADE)
    Post = models.ForeignKey(Post, related_name='likes',
        on_delete = models.CASCADE)

social_site/feed/forms.py
from django import forms
from .models import Post,Comment,Like

class NewPostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ['description','pic','tags']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pic'].widget.attrs.update({'enctype': 'multipart/form-data'})
        self.fields['tags'].widget.attrs.update({'placeholder':'enter tags'})


class NewCommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['message']

social_site/feed/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from .models import Post, Comment, Like
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth import get_user_model
from accounts.models import Profile
from django.urls import reverse_lazy,reverse
from braces.views import SelectRelatedMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse, JsonResponse
import json


User = get_user_model()
# Create your views here.

class PostListView(generic.ListView):
    model = Post
    template_name = 'feed/post_list.html'
    context_object_name = 'posts'
    paginate_by = 10
    ordering = ['-date_posted']
    def get_context_data(self,**kwargs):
        context = super(PostListView,self).get_context_data(**kwargs)
        if(self.request.user.is_authenticated):
            # find the list of liked posts
            liked = [i for i in Post.objects.all() if Like.objects.filter(Post=i, user=self.request.user)]
            context['liked_posts'] = liked
        return context

    def get_queryset(self,**kwargs):
        return Post.objects.exclude(user=self.request.user).order_by('-date_posted')

class UserPostListView(LoginRequiredMixin,generic.ListView):
    model = Post
    template_name = 'feed/UserPosts.html'
    context_object_name = 'posts'
    paginate_by = 10
    ordering = ['date_posted']

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        profile = get_object_or_404(Profile, slug=self.kwargs.get('slug'))
        user = profile.user
        liked = [i for i in Post.objects.all() if Like.objects.filter(Post=i, user=user)]
        context['liked_posts'] = liked
        context['by_user']=user
        return context

    def get_queryset(self,**kwargs):
        profile = get_object_or_404(Profile, slug=self.kwargs.get('slug'))
        user = profile.user
        return Post.objects.filter(user=user).order_by('-date_posted')

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'feed/post_detail.html'
    context_object_name = 'post'

    def get_queryset(self,**kwargs):
        queryset = super().get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))
        # post = Post.objects.filter(pk=self.kwargs.get('pk')).first()
        # return post
    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        post = get_object_or_404(Post,pk=self.kwargs.get('pk'))
        is_liked = Like.objects.filter(user=self.request.user,Post=post)
        liked_by = Like.objects.filter(Post=post)
        context['is_liked'] = is_liked
        context['liked_by'] = liked_by
        return context

class CreatePost(LoginRequiredMixin,generic.CreateView):
    model = Post
    form_class = forms.NewPostForm
    template_name = 'feed/create_post.html'
    success_url = reverse_lazy('feed:post_list_view')

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    # def get_success_url(self):
    #     return reverse_lazy('feed:post_list_view')


# note below that the order LoginRequiredMixin, UserPassesTestMixin, UpdateView
# is important as if we put generic.UpdateView at first position, any user(even not logged in)
# will be allowed to update a post by any other user which we don't want
class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,generic.UpdateView):

    model = Post
    fields = ['description','pic','tags']
    template_name = 'feed/update_post.html'
    # success_url = reverse_lazy('feed:user_posts', kwargs={'slug':user.profile.slug})

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    # user has to pass the below test function to be able to update a post
    # this comes with UserPassesTestMixin
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False

    def get_success_url(self):
        user = get_object_or_404(User,username__iexact=self.request.user.username)
        return reverse_lazy('feed:user_posts',kwargs={'slug':user.profile.slug})

class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,generic.DeleteView):
    model = Post
    success_url = reverse_lazy('feed:post_list_view')
    # template_name = 'feed/post_confirm_delete.html'

    # def get_object(slef,*args,**kwargs):
    #     return get_object_or_404(Post,pk=kwargs.get('pk'))

    def get_queryset(self,**kwargs):
        queryset = super().get_queryset()
        # print(self.kwargs)
        # print(kwargs)
        return queryset.filter(pk=self.kwargs.get('pk'))

    # user has to pass the below test function to be able to update a post
    # this comes with UserPassesTestMixin
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

@login_required
def like(request,pk):
    # post_pk = request.GET.get('likeId','')
    # print(request.GET)
    # print("pk is {}".format(post_pk))
    user = request.user
    post = get_object_or_404(Post, pk=pk)
    like = Like.objects.filter(Post=post).filter(user=request.user)
    liked = False
    if like:
        like.delete()
    else:
        liked = True
        Like.objects.create(Post=post, user=request.user)
    resp = {'liked':liked}
    response = json.dumps(resp)

    # request.META['HTTP_REFERER'] will keep the user on the same page
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

class SearchPosts(generic.ListView):
    model = Post
    template_name = 'feed/search_posts.html'
    paginate_by = 10
    ordering = ['-date_posted']
    def get_queryset(self):
        query = self.request.GET.get('post_tags')
        list = Post.objects.filter(tags__icontains=query).order_by('-date_posted')
        return list
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        c = self.request.GET.get('post_tags')
        context['tags']=c
        return context

class CommentView(LoginRequiredMixin,generic.CreateView):
    model = Comment
    form_class = forms.NewCommentForm
    template_name = 'feed/comment_form.html'
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.Post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        print(self.object)
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('feed:post_detail_view',kwargs={'pk':self.kwargs.get('pk')})
        # return HttpResponseRedirect(self.request.META['HTTP_REFERER'])

class PostCommentList(generic.ListView):
    model = Comment
    paginate_by = 10
    template_name = 'feed/post_comments.html'

    def get_queryset(self,**kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        # return ['test']
        return post.comments.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        context['post'] = post
        return context

social_site/feed/templates/feed/UserPosts.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <h1>Posts by {{user}} </h1>
  <div class="">
    <ul>
      {% for post in posts  %}
        {% include 'feed/_post.html' %}
      {%endfor%}
    </ul>
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

social_site/feed/templates/feed/_post.html
<!-- template for a single post in post list view -->

<div class="post">
  <div class="profile">
    <a href="{% url 'accounts:user_profile' slug=post.user.profile|slugify %}">
      <br>
      <img class='rounded-circle account-img' style='margin-bottom:1em' src="{{ post.user.profile.image.url }}" alt="" width="40em" height="40em">
      <p style="font-weight:bold;font-style:italic;display:inline;font-size:2em;">{{post.user}}</p>
    </a>
  </div>
  <div class="post_content">
    <a href="{% url 'feed:post_detail_view' pk=post.pk %}" >
      <img src="{{post.pic.url}}" alt="" width="50%" height="300">
      <br>
        {{post}}
      <br>
        posted on {{post.date_posted}}
      <br>
        tags: {{post.tags}}
      <br>
    </a>

    <p>{{ post.likes.count }} Like{{post.likes.count|pluralize}}
    {% if user != post.user %}
     {% if post in liked_posts %}
         <a href="{% url 'feed:post_like' pk=post.pk %}" style="color:blue"><span class='glyphicon glyphicon-thumbs-up'></span></a>
     {% else %}
         <a href="{% url 'feed:post_like' pk=post.pk %}" style="color:black"><span class='glyphicon glyphicon-thumbs-up'></span></a>
     {% endif %}
    {% endif %}

    <br>
    <a href="{% url 'feed:post_comments' pk=post.pk%}">
      {{post.comments.count}} comment{{post.comments.count|pluralize}}
    </a>
    {% if user != post.user %}
      <a href="{% url 'feed:new_comment' pk=post.pk%}">
      <span class="glyphicon glyphicon-comment" style="color:black" ></span></a>
    {% endif %}

    {% if user == post.user %}
    <br>
      <a href="{%url 'feed:post_update' pk=post.pk %}" class="btn btn-info btn-large">update post </a>
      <a href="{%url 'feed:post_delete' pk=post.pk %}" class="btn btn-small btn-danger ">Delete post</a>
    {% endif %}
    </p>
    <br><br>
  </div>

</div>

social_site/feed/templates/feed/comment_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <form class="" action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Post comment" class="btn btn-simple">
  </form>
{% endblock %}

social_site/feed/templates/feed/create_post.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
  <h4>New Post</h4>
  <form class="" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Post" class='btn btn-primary btn-large'>
  </form>
{% endblock %}

social_site/feed/templates/feed/post_comments.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  These are the comments on the post : <br>
   <p style="font-style:italic;">
     <img src="{{post.pic.url}}" alt="" width='200px' height='200px'>
     <br>
     {{post}}
   </p>
   <hr style="height:1px;border:none;color:#333;background-color:#333;">
    {% if object_list|length == 0 %}
      No comments yet
    {% endif %}

    {% for i in object_list %}
        <p>{{i.message}}
          <br>
          by
          <a href="{% url 'accounts:user_profile' slug=i.user.profile.slug %}">
            {{i.user.profile}}
          </a>
        </p>
    {% endfor %}

{% endblock %}

social_site/feed/templates/feed/post_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
  <h2>Are you sure you want to delete {{object}}?</h2>


  <form class="" action="" method="post">
    {% csrf_token %}
    <input type="submit" name="" value="Confirm" class="btn btn-danger btn-large">
    <br>
    <br>
    <a href="{% url 'feed:post_list_view' %}" class="btn btn-simple btn-secondary ">Cancel</a>
  </form>
{% endblock %}

social_site/feed/templates/feed/post_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{post.description}}</h1>
  <a href="{{post.pic.url}}"><img src="{{post.pic.url}}" alt="" width="400" height="400"></a>

  <p>
    <div class="post_info">
      by
      <a href="#">{{post.user.profile}}</a>
      <br>
      tags : {{post.tags}}
      <br>
      posted_on : {{post.date_posted}}
    </div>

    {{ post.likes.count }} Like{{post.likes.count|pluralize}}

  {% if user != post.user %}
   {% if post in liked_posts %}
       <a href="{% url 'feed:post_like' pk=post.pk %}" style="color:blue"><span class='glyphicon glyphicon-thumbs-up'></span></a>
   {% else %}
       <a href="{% url 'feed:post_like' pk=post.pk %}" style="color:black"><span class='glyphicon glyphicon-thumbs-up'></span></a>
   {% endif %}
  {% endif %}
  <br>
  {{post.comments.count}} comment{{post.comments.count|pluralize}}
  {% if user != post.user %}
    <a href="{% url 'feed:new_comment' pk=post.pk%}">
      <span class="glyphicon glyphicon-comment" style="color:black" ></span></a>
  {% endif %}

  {% if user == post.user %}
  <br>
    <a href="{%url 'feed:post_update' pk=post.pk %}" class="btn btn-info btn-large">update post </a>
    <a href="{%url 'feed:post_delete' pk=post.pk %}" class="btn btn-small btn-danger ">Delete post</a>
  {% endif %}
  </p>
{% endblock %}

social_site/feed/templates/feed/post_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<form action="{% url 'feed:search_posts' %}" method="get">
  <input type="text" name="post_tags" placeholder="search">
</form>
  <div class="">
  <h1>Posts by other users :  </h1>
      {% for post in page_obj  %}
        {% if post.user != user %}
          {% include 'feed/_post.html' %}
        {% endif %}
      {%endfor%}
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

social_site/feed/templates/feed/search_posts.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<form action="{% url 'feed:search_posts' %}" method="get">
  <input type="text" name="post_tags" placeholder="search post based on tags">
</form>
  <h1>Posts by other users containing tag : "{{tags}}"  </h1>
  <div class="">
    <ul>
      {% for post in object_list  %}
        {% if post.user != user %}
          {% include 'feed/_post.html' %}
        {% endif %}
      {%endfor%}
    </ul>

  </div>
{% endblock %}

social_site/feed/templates/feed/update_post.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
  <h4>Update Post</h4>
  <form class="" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Update Post" class='btn btn-primary btn-large'>
  </form>
{% endblock %}